### ISSUE TITLE
Layout Directory search returning mixed content warning and 404 error

### ISSUE THREAD

**Issue by Misplon** [siteorigin/layout-viewer#2]
@AlexGStapleton and I came across this while doing WP 5.3 testing.

To recreate, go to `Layouts > Layouts Directory` and do a search. Open the console.

Mixed content errors are thrown because we're loading from `http`.

There is a 404.

<img width="1670" alt="Edit_Page_‹_Cape_Town_Ship_Suppliers___Exporters__Pty__Ltd_—_WordPress" src="https://user-images.githubusercontent.com/789159/66707004-a3975200-ed3a-11e9-8e1b-0ce7c7e516e3.png">

**Comment by Misplon** [comment]
I've resolved the mixed content issue by switching layouts.siteorigin.com to https.

**Comment by AlexGStapleton** [comment]
I've run some tests and this issue is caused by the returned JSON from layouts.siteorigin.com. This is the response from layouts.siteorigin.com when a user searches for something with no results:

`{"items":[{"id":null,"slug":null,"title":null,"description":null,"preview":false,"screenshot":false},{"id":null,"slug":null,"title":null,"description":null,"preview":false,"screenshot":false}],"found":0,"max_num_pages":0}{"title":"Layouts Directory - Results For: <em>test<\/em>","items":[{"id":null,"slug":null,"title":null,"description":null,"preview":false,"screenshot":false,"type":"directory-siteorigin"},{"id":null,"slug":null,"title":null,"description":null,"preview":false,"screenshot":false,"type":"directory-siteorigin"}],"max_num_pages":0}`

Multiple results are returned, but they're all empty. The Prebuilt Layout directory will output any results regardless of whether the data is "empty" or not ([reference](https://github.com/siteorigin/siteorigin-panels/blob/2.10.11/inc/admin-layouts.php#L247). This leads me to believe there was a change on layouts.siteorigin.com that caused this issue rather than in the Prebuilt Layout search code.

I see two ways forward:

1. Prevent the Layout Directory from running an item if key data is missing (id, slug, title, etc)
2. Account for empty items in SiteOrigin Page Builder.

The latter option won't resolve this issue for older versions of SiteOrigin Page Builder.

**Comment by gregpriday** [comment]
Thanks @AlexGStapleton - option 1 did the trick.
